version: '3.8'
services:
  redis:
    image: redis:7
    container_name: redis
    ports: ["6379:6379"]

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: finance
      MYSQL_USER: finuser
      MYSQL_PASSWORD: finpass
    command: --default-authentication-plugin=mysql_native_password
    ports: ["3306:3306"]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 10

  transaction-gateway:
    build: ./transaction-gateway
    depends_on:
      redis:
        condition: service_started
      register-service:
        condition: service_started
      report-service:
        condition: service_started
    environment:
      - REDIS_URL=redis://redis:6379
      - REGISTER_URL=http://register-service:4000
      - REPORT_URL=http://report-service:5000
    ports: ["3000:3000"]

  register-service:
    build: ./register-service
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_URL=mysql+pymysql://finuser:finpass@mysql/finance
    ports: ["4000:4000"]

  report-service:
    build: ./report-service
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_URL=mysql+pymysql://finuser:finpass@mysql/finance
    ports: ["5000:5000"]